<a href="https://colab.research.google.com/github/hebaismail6848/Amit-assignments/blob/main/Ensemble_learning_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Decision_tree

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.datasets import load_iris
from sklearn.metrics import accuracy_score

In [ ]:
iris=load_iris()
x_train,x_test,y_train,y_test=train_test_split(iris.data,iris.target,test_size=.2,random_state=42)

In [ ]:
clf=DecisionTreeClassifier()
clf.fit(x_train,y_train)

DecisionTreeClassifier()

In [ ]:
y_pred=clf.predict(x_test)
y_pred

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0])

In [ ]:
accuracy=accuracy_score(y_test,y_pred)
print(accuracy)

1.0


#Bagging(same model)

In [ ]:
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier

In [ ]:
iris=load_iris()
x_train,x_test,y_train,y_test=train_test_split(iris.data,iris.target,test_size=.2,random_state=42)

In [ ]:
bag_clf=BaggingClassifier(
    base_estimator=DecisionTreeClassifier(),
    n_estimators=500,
    bootstrap=True,
    n_jobs=-1
)

In [ ]:
bag_clf.fit(x_train,y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(


BaggingClassifier(base_estimator=DecisionTreeClassifier(), n_estimators=500,
                  n_jobs=-1)

In [ ]:
y_pred=bag_clf.predict(x_test)
y_pred

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0])

In [ ]:
accuracy=accuracy_score(y_test,y_pred)
accuracy

1.0

#Bagging(different model)

In [ ]:
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
iris=load_iris()
x_train,x_test,y_train,y_test=train_test_split(iris.data,iris.target,test_size=.2,random_state=42)

In [ ]:
tree_clf=DecisionTreeClassifier()
logis_clf=LogisticRegression()
knn_clf=KNeighborsClassifier()

In [ ]:
tree_bagging=BaggingClassifier(
    base_estimator=tree_clf,
    n_estimators=500,
    bootstrap=True,
    random_state=42
)
logis_bagging=BaggingClassifier(
    base_estimator=logis_clf,
    n_estimators=500,
    bootstrap=True,
    random_state=42
)

knn_bagging=BaggingClassifier(
    base_estimator=knn_clf,
    n_estimators=500,
    bootstrap=True,
    random_state=42
)


In [ ]:
#tree
tree_bagging.fit(x_train,y_train)
tree_pred= tree_bagging.predict(x_test)

#logistic
logis_bagging.fit(x_train,y_train)
logis_pred= logis_bagging.predict(x_test)

#knn
knn_bagging.fit(x_train,y_train)
knn_pred= knn_bagging.predict(x_test)

/usr/local/lib/python3.10/dist-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs fail

In [ ]:
print(tree_pred)
print('**********************')
print(logis_pred)
print('**********************')
print(knn_pred)

[1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0]
**********************
[1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0]
**********************
[1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0]


In [ ]:
final_pred=np.round((tree_pred +logis_pred +knn_pred) / 3 )
final_pred

array([1., 0., 2., 1., 1., 0., 1., 2., 1., 1., 2., 0., 0., 0., 0., 1., 2.,
       1., 1., 2., 0., 2., 0., 2., 2., 2., 2., 2., 0., 0.])

In [ ]:
accuracy=accuracy_score(y_test,final_pred)
accuracy

1.0

#Bagging(Random_forest)

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier

In [ ]:
iris=load_iris()
x_train,x_test,y_train,y_test=train_test_split(iris.data,iris.target,test_size=.2,random_state=42)

In [ ]:
bag_clf=RandomForestClassifier(
    n_estimators=500,
    bootstrap=True,
    n_jobs=-1
)

In [ ]:
bag_clf.fit(x_train,y_train)

RandomForestClassifier(n_estimators=500, n_jobs=-1)

In [ ]:
y_pred=bag_clf.predict(x_test)
y_pred

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0])

In [ ]:
accuracy=accuracy_score(y_test,y_pred)
accuracy

1.0

#AdaBoost

In [ ]:
from sklearn.ensemble import AdaBoostClassifier

In [ ]:
iris=load_iris()
x_train,x_test,y_train,y_test=train_test_split(iris.data,iris.target,test_size=.2,random_state=42)

In [ ]:
Ada_boost=AdaBoostClassifier(

    base_estimator=DecisionTreeClassifier(max_depth=1),
    n_estimators=200,
    learning_rate=.5,
    random_state=42
)

In [ ]:
Ada_boost.fit(x_train,y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(


AdaBoostClassifier(base_estimator=DecisionTreeClassifier(max_depth=1),
                   learning_rate=0.5, n_estimators=200, random_state=42)

In [ ]:
y_pred=Ada_boost.predict(x_test)
y_pred

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 1,
       0, 2, 2, 2, 2, 2, 0, 0])

In [ ]:
accuracy=accuracy_score(y_pred,y_test)
print(accuracy)

0.9666666666666667
