<a href="https://colab.research.google.com/github/hebaismail6848/Amit-assignments/blob/main/preprocessing_NLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Tokenizer


In [ ]:
import nltk      # Natural language toolkit
# nltk.download()  # download the necessary dataset, puckages, libraries(load memories)
nltk.download('punkt')  # download the punkt resource,This resource is required for tokenization, including sentence tokenization and word tokenization.

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [ ]:
# tokenize the text into individual sentences
text = "Hello! How are you doing today? I hope you're having a good day."
sentences = nltk.sent_tokenize(text)
tokens = nltk.word_tokenize(text)
print(sentences)
print(tokens)

['Hello!', 'How are you doing today?', "I hope you're having a good day."]
['Hello', '!', 'How', 'are', 'you', 'doing', 'today', '?', 'I', 'hope', 'you', "'re", 'having', 'a', 'good', 'day', '.']


#Stop words

In [ ]:
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


##stop words in Arabic

In [ ]:
stopwords.words('arabic')

['إذ',
 'إذا',
 'إذما',
 'إذن',
 'أف',
 'أقل',
 'أكثر',
 'ألا',
 'إلا',
 'التي',
 'الذي',
 'الذين',
 'اللاتي',
 'اللائي',
 'اللتان',
 'اللتيا',
 'اللتين',
 'اللذان',
 'اللذين',
 'اللواتي',
 'إلى',
 'إليك',
 'إليكم',
 'إليكما',
 'إليكن',
 'أم',
 'أما',
 'أما',
 'إما',
 'أن',
 'إن',
 'إنا',
 'أنا',
 'أنت',
 'أنتم',
 'أنتما',
 'أنتن',
 'إنما',
 'إنه',
 'أنى',
 'أنى',
 'آه',
 'آها',
 'أو',
 'أولاء',
 'أولئك',
 'أوه',
 'آي',
 'أي',
 'أيها',
 'إي',
 'أين',
 'أين',
 'أينما',
 'إيه',
 'بخ',
 'بس',
 'بعد',
 'بعض',
 'بك',
 'بكم',
 'بكم',
 'بكما',
 'بكن',
 'بل',
 'بلى',
 'بما',
 'بماذا',
 'بمن',
 'بنا',
 'به',
 'بها',
 'بهم',
 'بهما',
 'بهن',
 'بي',
 'بين',
 'بيد',
 'تلك',
 'تلكم',
 'تلكما',
 'ته',
 'تي',
 'تين',
 'تينك',
 'ثم',
 'ثمة',
 'حاشا',
 'حبذا',
 'حتى',
 'حيث',
 'حيثما',
 'حين',
 'خلا',
 'دون',
 'ذا',
 'ذات',
 'ذاك',
 'ذان',
 'ذانك',
 'ذلك',
 'ذلكم',
 'ذلكما',
 'ذلكن',
 'ذه',
 'ذو',
 'ذوا',
 'ذواتا',
 'ذواتي',
 'ذي',
 'ذين',
 'ذينك',
 'ريث',
 'سوف',
 'سوى',
 'شتان',
 'عدا',
 'عسى',
 'عل'

In [ ]:
# Define a sample Arabic text
arabic_text ="قامت الشركة بإصدار بيانات تفصيلية حول أدائها في الربع الأول من العام الحالي"

# Tokenize the text into words
words = word_tokenize(arabic_text)
print(len(words))
print(words)

13
['قامت', 'الشركة', 'بإصدار', 'بيانات', 'تفصيلية', 'حول', 'أدائها', 'في', 'الربع', 'الأول', 'من', 'العام', 'الحالي']


In [ ]:
# Load the Arabic stop words
stop_words = set(stopwords.words('arabic'))
stop_words

{'ء',
 'ءَ',
 'آ',
 'آب',
 'آذار',
 'آض',
 'آمينَ',
 'آناء',
 'آنفا',
 'آه',
 'آها',
 'آهاً',
 'آهٍ',
 'آهِ',
 'آي',
 'أ',
 'أبدا',
 'أبريل',
 'أبو',
 'أبٌ',
 'أجل',
 'أجمع',
 'أحد',
 'أخبر',
 'أخذ',
 'أخو',
 'أخٌ',
 'أربع',
 'أربعاء',
 'أربعة',
 'أربعمئة',
 'أربعمائة',
 'أرى',
 'أسكن',
 'أصبح',
 'أصلا',
 'أضحى',
 'أطعم',
 'أعطى',
 'أعلم',
 'أغسطس',
 'أف',
 'أفريل',
 'أفعل به',
 'أفٍّ',
 'أقبل',
 'أقل',
 'أكتوبر',
 'أكثر',
 'أل',
 'ألا',
 'ألف',
 'ألفى',
 'أم',
 'أما',
 'أمام',
 'أمامك',
 'أمامكَ',
 'أمد',
 'أمس',
 'أمسى',
 'أمّا',
 'أن',
 'أنا',
 'أنبأ',
 'أنت',
 'أنتم',
 'أنتما',
 'أنتن',
 'أنتِ',
 'أنشأ',
 'أنى',
 'أنًّ',
 'أنّى',
 'أهلا',
 'أو',
 'أوت',
 'أوشك',
 'أول',
 'أولئك',
 'أولاء',
 'أولالك',
 'أوه',
 'أوّهْ',
 'أى',
 'أي',
 'أيا',
 'أيار',
 'أيضا',
 'أيلول',
 'أين',
 'أينما',
 'أيها',
 'أيّ',
 'أيّان',
 'أُفٍّ',
 'ؤ',
 'إحدى',
 'إذ',
 'إذا',
 'إذاً',
 'إذما',
 'إذن',
 'إزاء',
 'إلا',
 'إلى',
 'إليك',
 'إليكم',
 'إليكما',
 'إليكن',
 'إليكنّ',
 'إليكَ',
 'إلَيْكَ',
 'إلّا',


In [ ]:
# Filter out the stop words from the text
filtered_words = [word for word in words if not word in stop_words]
print(filtered_words)
print(len(filtered_words))

['قامت', 'الشركة', 'بإصدار', 'بيانات', 'تفصيلية', 'حول', 'أدائها', 'الربع', 'الأول', 'العام', 'الحالي']
11


In [ ]:
# Join the filtered words into a string
filtered_text = ' '.join(filtered_words)

# Print the filtered text
print(filtered_text)

قامت الشركة بإصدار بيانات تفصيلية حول أدائها الربع الأول العام الحالي


##stop words in english

In [ ]:
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [ ]:
# Define a sample English text
english_text = "Hello, how are you doing? i hope you are doing well."

# Tokenize the text into words
words = word_tokenize(english_text)
print(words)
print(len(words))

['Hello', ',', 'how', 'are', 'you', 'doing', '?', 'i', 'hope', 'you', 'are', 'doing', 'well', '.']
14


In [ ]:
# Load the English stop words
stop_words = set(stopwords.words('english'))

# Filter out the stop words from the text
filtered_words = [word for word in words if not word in stop_words]

print(filtered_words)
print(len(filtered_words))

['Hello', ',', '?', 'hope', 'well', '.']
6


In [ ]:
# Join the filtered words into a string
filtered_text = ' '.join(filtered_words)

# Print the filtered text
print(filtered_text)

#you can exlude some words in stop of words if you see the result nit good

Hello , ? hope well .


#Stemming

In [ ]:
import nltk
from nltk.stem import PorterStemmer

In [ ]:
# Create a stemmer object
stemmer = PorterStemmer()

# Stem some example words
words = ["walking", "jumps", "jumped", "jumping"]
for word in words:
    stemmed_word = stemmer.stem(word)
    print(f"{word} -> {stemmed_word}")

walking -> walk
jumps -> jump
jumped -> jump
jumping -> jump


#Lemitaziation

In [ ]:
import nltk
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...


True

In [ ]:
from nltk.stem import PorterStemmer, WordNetLemmatizer
from nltk.tokenize import word_tokenize

text = "The quick brown foxes jumped over the lazy dogs"

# Stemming
stemmer = PorterStemmer()
stemmed_words = [stemmer.stem(word) for word in word_tokenize(text)]
print(stemmed_words)

# Lemmatization
lemmatizer = WordNetLemmatizer()
lemmatized_words = [lemmatizer.lemmatize(word) for word in word_tokenize(text)]
print(lemmatized_words)

#look for the lazy

['the', 'quick', 'brown', 'fox', 'jump', 'over', 'the', 'lazi', 'dog']
['The', 'quick', 'brown', 'fox', 'jumped', 'over', 'the', 'lazy', 'dog']


#regex

##extract a digits

In [ ]:
import re

text='''
Elon musk's phone number is 9991116666, call him if you have any questions on dodgecoin.
Tesla's revenue is 40 billion
Tesla's CFO number (999)-333-7777
'''

In [ ]:
pattern = '\d{3}'
matches = re.findall(pattern, text)
matches

['999', '111', '666', '999', '333', '777']

In [ ]:
pattern = '\(\d{3}\)-\d{3}-\d{4}'
matches = re.findall(pattern, text)
matches

['(999)-333-7777']

In [ ]:

pattern = '\(\d{3}\)-\d{3}-\d{4}|\d{10}'

matches = re.findall(pattern, text)
matches

['9991116666', '(999)-333-7777']

##extract a head line

1- Note 1 - Overview

2- Note 2 - Summary of Significant Accounting Policies

In [ ]:
text = '''
Note 1 - Overview
Tesla, Inc. (“Tesla”, the “Company”, “we”, “us” or “our”) was incorporated in the State of Delaware on July 1, 2003. We design, develop, manufacture and sell high-performance fully electric vehicles and design, manufacture, install and sell solar energy generation and energy storage
products. Our Chief Executive Officer, as the chief operating decision maker (“CODM”), organizes our company, manages resource allocations and measures performance among two operating and reportable segments: (i) automotive and (ii) energy generation and storage.
Beginning in the first quarter of 2021, there has been a trend in many parts of the world of increasing availability and administration of vaccines
against COVID-19, as well as an easing of restrictions on social, business, travel and government activities and functions. On the other hand, infection
rates and regulations continue to fluctuate in various regions and there are ongoing global impacts resulting from the pandemic, including challenges
and increases in costs for logistics and supply chains, such as increased port congestion, intermittent supplier delays and a shortfall of semiconductor
supply. We have also previously been affected by temporary manufacturing closures, employment and compensation adjustments and impediments to
administrative activities supporting our product deliveries and deployments.
Note 2 - Summary of Significant Accounting Policies
Unaudited Interim Financial Statements
The consolidated balance sheet as of September 30, 2021, the consolidated statements of operations, the consolidated statements of
comprehensive income, the consolidated statements of redeemable noncontrolling interests and equity for the three and nine months ended September
30, 2021 and 2020 and the consolidated statements of cash flows for the nine months ended September 30, 2021 and 2020, as well as other information
disclosed in the accompanying notes, are unaudited. The consolidated balance sheet as of December 31, 2020 was derived from the audited
consolidated financial statements as of that date. The interim consolidated financial statements and the accompanying notes should be read in
conjunction with the annual consolidated financial statements and the accompanying notes contained in our Annual Report on Form 10-K for the year
ended December 31, 2020.
'''


#.>>>> distance
#[^a]>>>exclude the a character
#*>>>>>> the rest of characters
#\n >>>> the new line
#note(x)>>> the result is only x without note

In [ ]:
pattern = 'Note.\d.-.[^\n]*'
matches = re.findall(pattern, text)
matches

['Note 1 - Overview', 'Note 2 - Summary of Significant Accounting Policies']

In [ ]:
pattern = 'Note.\d.-.([^\n]*)'
matches = re.findall(pattern, text)
matches

['Overview', 'Summary of Significant Accounting Policies']

##Extract that "['FY2021 Q1', 'fy2020 Q4']"

In [ ]:
text = '''
The gross cost of operating lease vehicles in FY2021 Q1 was $4.85 billion.
In previous quarter i.e. fy2020 Q4 it was $3 billion fy2020 Q5.
'''
#['FY2021 Q1', 'fy2020 Q4']

In [ ]:
pattern = 'FY\d{4} Q[1-4]'

matches = re.findall(pattern, text, flags=re.IGNORECASE)
matches

['FY2021 Q1', 'fy2020 Q4']

##Extract only financial numbers

---



In [ ]:
text = '''
Tesla's gross cost of operating lease vehicles in FY2021 Q1 was $4.85 billion.
In previous quarter i.e. FY2020 Q4 it was $3 billion.
'''

In [ ]:
# ( $4.85 , $3)

pattern = '\$[0-9\.]+'

matches = re.findall(pattern, text, flags=re.IGNORECASE)
matches


# $ is special character, if you want $ as it write that \$
# . referes to any thing, if you want . as it write that \.

['$4.85', '$3']

In [ ]:
# ( 4.85 , 3)  >>> use () to exclude the $

pattern = '\$([0-9\.]+)'

matches = re.findall(pattern, text, flags=re.IGNORECASE)
matches


['4.85', '3']

##Extract periods and financial numbers both


In [ ]:
# ['FY2021 Q1 was $4.85', 'FY2020 Q4 it was $3']
text = '''
Tesla's gross cost of operating lease vehicles in FY2021 Q1 was $4.85 billion.
In previous quarter i.e. FY2020 Q4 it was $3 billion.
'''
pattern ='(FY\d{4}.Q[1-4][^\$]+\$[0-9\.]+)'
# pattern ='FY(\d{4} Q[1-4])[^\$]+\$([0-9\.]+)'

matches = re.findall(pattern, text)
matches

# ( ) seperate the value which in () about other
# [^a] exclude a character

['FY2021 Q1 was $4.85', 'FY2020 Q4 it was $3']

In [ ]:
# [('2021 Q1', '4.85'), ('2020 Q4', '3')]

text = '''
Tesla's gross cost of operating lease vehicles in FY2021 Q1 was $4.85 billion.
In previous quarter i.e. FY2020 Q4 it was $3 billion.
'''
pattern ='FY(\d{4}.Q[1-4])[^\$]+\$([0-9\.]+)'

matches = re.findall(pattern, text)
matches

[('2021 Q1', '4.85'), ('2020 Q4', '3')]

##search pattern

1- search  >>>>>return the first pattern achieve the condition.

2- findall  >>>>>return all the patterns achieve the condition

3- use groups() to print it

In [ ]:
# [('2021 Q1', '4.85'), ('2020 Q4', '3')]

text = '''
Tesla's gross cost of operating lease vehicles in FY2021 Q1 was $4.85 billion.
In previous quarter i.e. FY2020 Q4 it was $3 billion.
'''
pattern ='FY(\d{4}.Q[1-4])[^\$]+\$([0-9\.]+)'

matches = re.search(pattern, text)
matches.groups()

('2021 Q1', '4.85')

##Task1

Extract all twitter handles from following text. Twitter handle is the text that appears after https://twitter.com/ and is a single word. Also it contains only alpha numeric characters i.e. A-Z a-z , o to 9 and underscore _

In [ ]:
text = '''
Follow our leader Elon musk on twitter here: https://twitter.com/elonmusk, more information
on Tesla's products can be found at https://www.tesla.com/. Also here are leading influencers
for tesla related news,
https://twitter.com/teslarati
https://twitter.com/dummy_tesla
https://twitter.com/dummy_2_tesla
'''
pattern = 'https:\/\/twitter\.com\/([A-Za-z0-9_]+)'

re.findall(pattern, text)

['elonmusk', 'teslarati', 'dummy_tesla', 'dummy_2_tesla']

##Task2
Extract Concentration Risk Types. It will be a text that appears after "Concentration Risk:", In below example, your regex should extract these two strings

(1) Credit Risk

(2) Supply Rish

In [ ]:
text = '''
Concentration of Risk: Credit Risk
Financial instruments that potentially subject us to a concentration of credit risk consist of cash, cash equivalents, marketable securities,
restricted cash, accounts receivable, convertible note hedges, and interest rate swaps. Our cash balances are primarily invested in money market funds
or on deposit at high credit quality financial institutions in the U.S. These deposits are typically in excess of insured limits. As of September 30, 2021
and December 31, 2020, no entity represented 10% or more of our total accounts receivable balance. The risk of concentration for our convertible note
hedges and interest rate swaps is mitigated by transacting with several highly-rated multinational banks.
Concentration of Risk: Supply Risk
We are dependent on our suppliers, including single source suppliers, and the inability of these suppliers to deliver necessary components of our
products in a timely manner at prices, quality levels and volumes acceptable to us, or our inability to efficiently manage these components from these
suppliers, could have a material adverse effect on our business, prospects, financial condition and operating results.
'''
# pattern = 'Concentration of Risk: ([A-Za-z]+.[[A-Za-z]+)'
pattern ='Concentration of Risk: (\w+\s*\w*)'

re.findall(pattern, text)

# \w small   >>> equal to [a-zA-Z0-9_]
# \W capital >>> the inverse of \w small
# +          >>> one or more
# \s small   >>> any whitespace character
# \S capital >>> not whitespace character
# + one or more
# * zero or more

['Credit Risk', 'Supply Risk']

##Task3

In [ ]:
import re
text='my name is ali and my salary : 10000'
pattern ='salary.:.([0-9]+)'
print(re.findall(pattern, text))
print(re.sub(pattern,'20000',text))

['10000']
my name is ali and my 20000


#POS(Part of speech)

1- token.pos_ >>>>>>>represent pos(verp, noun,....)

2- spacy.explain(token.pos_)   >>>>>akes the part-of-speech tag as an argument and returns a brief explanation of what the pos represents.

3- token.tag_  >>>> tell me the tense(الزمن  بتاعى )

4- spacy.explain(token.tag_ ) >>>> returns a brief explanation of what the tag represents

In [ ]:
import spacy
!python -m spacy download en_core_web_sm

# en_core_web_sm  >>>>>> pre-trained model is designed for processing English text for tasks such as
# part-of-speech tagging, named entity recognition, and dependency parsing.

In [ ]:
nlp = spacy.load("en_core_web_sm")
doc = nlp("Elon flew to mars yesterday. He carried biryani masala with him")

for token in doc:
    print(token,"||", token.pos_,"||", spacy.explain(token.pos_))

Elon || PROPN || proper noun
flew || VERB || verb
to || ADP || adposition
mars || NOUN || noun
yesterday || NOUN || noun
. || PUNCT || punctuation
He || PRON || pronoun
carried || VERB || verb
biryani || ADJ || adjective
masala || NOUN || noun
with || ADP || adposition
him || PRON || pronoun


In [ ]:
doc = nlp("Wow! Dr. Strange made 265 million $ on the very first day")

for token in doc:
    print(token," | ", token.pos_, " | ", spacy.explain(token.pos_), " | ", token.tag_, " | ", spacy.explain(token.tag_))

Wow  |  INTJ  |  interjection  |  UH  |  interjection
!  |  PUNCT  |  punctuation  |  .  |  punctuation mark, sentence closer
Dr.  |  PROPN  |  proper noun  |  NNP  |  noun, proper singular
Strange  |  PROPN  |  proper noun  |  NNP  |  noun, proper singular
made  |  VERB  |  verb  |  VBD  |  verb, past tense
265  |  NUM  |  numeral  |  CD  |  cardinal number
million  |  NUM  |  numeral  |  CD  |  cardinal number
$  |  NUM  |  numeral  |  CD  |  cardinal number
on  |  ADP  |  adposition  |  IN  |  conjunction, subordinating or preposition
the  |  DET  |  determiner  |  DT  |  determiner
very  |  ADV  |  adverb  |  RB  |  adverb
first  |  ADJ  |  adjective  |  JJ  |  adjective (English), other noun-modifier (Chinese)
day  |  NOUN  |  noun  |  NN  |  noun, singular or mass


##using pos as a filter for Removing all SPACE, PUNCT and X token from text

In [ ]:
earnings_text="""Microsoft Corp. today announced the following results for the quarter ended December 31, 2021, as compared to the corresponding period of last fiscal year:

·         Revenue was $51.7 billion and increased 20%
·         Operating income was $22.2 billion and increased 24%
·         Net income was $18.8 billion and increased 21%
·         Diluted earnings per share was $2.48 and increased 22%
“Digital technology is the most malleable resource at the world’s disposal to overcome constraints and reimagine everyday work and life,” said Satya Nadella, chairman and chief executive officer of Microsoft. “As tech as a percentage of global GDP continues to increase, we are innovating and investing across diverse and growing markets, with a common underlying technology stack and an operating model that reinforces a common strategy, culture, and sense of purpose.”
“Solid commercial execution, represented by strong bookings growth driven by long-term Azure commitments, increased Microsoft Cloud revenue to $22.1 billion, up 32% year over year” said Amy Hood, executive vice president and chief financial officer of Microsoft."""

doc = nlp(earnings_text)

filtered_tokens = []

for token in doc:
    if token.pos_ not in ["SPACE", "PUNCT", "X"]:
        filtered_tokens.append(token)

In [ ]:
filtered_tokens[:10]

[Microsoft,
 Corp.,
 today,
 announced,
 the,
 following,
 results,
 for,
 the,
 quarter]

##get the count of each pos

In [ ]:
count = doc.count_by(spacy.attrs.POS)
count

{96: 13,
 92: 46,
 100: 24,
 90: 9,
 85: 16,
 93: 16,
 97: 27,
 98: 1,
 84: 20,
 103: 10,
 87: 6,
 99: 5,
 89: 12,
 86: 3,
 94: 3,
 95: 2}

In [ ]:
doc.vocab[96].text

'PROPN'

In [ ]:
count.items()

dict_items([(96, 13), (92, 46), (100, 24), (90, 9), (85, 16), (93, 16), (97, 27), (98, 1), (84, 20), (103, 10), (87, 6), (99, 5), (89, 12), (86, 3), (94, 3), (95, 2)])

In [ ]:
for k,v in count.items():
    print(doc.vocab[k].text, "|",v)

PROPN | 13
NOUN | 46
VERB | 24
DET | 9
ADP | 16
NUM | 16
PUNCT | 27
SCONJ | 1
ADJ | 20
SPACE | 10
AUX | 6
SYM | 5
CCONJ | 12
ADV | 3
PART | 3
PRON | 2


##apply pos using ntlk not spacy

In [ ]:
import nltk
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')

text = "The quick brown fox jumps over the lazy dog."

# Tokenize the text into individual words
words = nltk.word_tokenize(text)

# Perform POS tagging on the tokenized words
pos_tags = nltk.pos_tag(words)

# Print the POS tags for each word
for word, tag in pos_tags:
    print(word, tag)

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.


The DT
quick JJ
brown NN
fox NN
jumps VBZ
over IN
the DT
lazy JJ
dog NN
. .


#Named Entity Recognition

In [ ]:
import spacy
nlp = spacy.load("en_core_web_sm")

# en_core_web_sm >>> small model
# en_core_web_md >>> meduim model
# en_core_web_lg >>> large model

In [ ]:
nlp.pipe_names
#the tasks which it will do

['tok2vec', 'tagger', 'parser', 'attribute_ruler', 'lemmatizer', 'ner']

In [ ]:
doc1 = nlp("Tesla Inc is going to acquire twitter for $45 billion")

for ent in doc.ents:
    print(ent.text, " | ", ent.label_, " | ", spacy.explain(ent.label_))

Tesla Inc  |  ORG  |  Companies, agencies, institutions, etc.
$45 billion  |  MONEY  |  Monetary values, including unit


In [ ]:
from spacy import displacy

displacy.render(doc1, style="ent")

# https://onecompiler.com/html/3zec3j8sc  >>> to show the result

'<div class="entities" style="line-height: 2.5; direction: ltr">\n<mark class="entity" style="background: #7aecec; padding: 0.45em 0.6em; margin: 0 0.25em; line-height: 1; border-radius: 0.35em;">\n    Tesla Inc\n    <span style="font-size: 0.8em; font-weight: bold; line-height: 1; border-radius: 0.35em; vertical-align: middle; margin-left: 0.5rem">ORG</span>\n</mark>\n is going to acquire twitter for \n<mark class="entity" style="background: #e4e7d2; padding: 0.45em 0.6em; margin: 0 0.25em; line-height: 1; border-radius: 0.35em;">\n    $45 billion\n    <span style="font-size: 0.8em; font-weight: bold; line-height: 1; border-radius: 0.35em; vertical-align: middle; margin-left: 0.5rem">MONEY</span>\n</mark>\n</div>'

In [ ]:
##List down all the entities
nlp.pipe_labels['ner']

['CARDINAL',
 'DATE',
 'EVENT',
 'FAC',
 'GPE',
 'LANGUAGE',
 'LAW',
 'LOC',
 'MONEY',
 'NORP',
 'ORDINAL',
 'ORG',
 'PERCENT',
 'PERSON',
 'PRODUCT',
 'QUANTITY',
 'TIME',
 'WORK_OF_ART']

In [ ]:
doc = nlp("Tesla Inc is going to acquire Twitter Inc for $45 billion")
for ent in doc.ents:
    print(ent.text, " | ", ent.label_, " | ", ent.start_char, "|", ent.end_char)

Tesla Inc  |  ORG  |  0 | 9
Twitter Inc  |  ORG  |  30 | 41
$45 billion  |  MONEY  |  46 | 57


In [ ]:
#Setting custom entities
doc = nlp("Tesla is going to acquire Twitter for $45 billion")
for ent in doc.ents:
    print(ent.text, " | ", ent.label_)


#here, when we deleted inc after twitter, the result was twiiter is product and that uncorrect so i need to handle in manually

Tesla  |  ORG
Twitter  |  PRODUCT
$45 billion  |  MONEY


In [ ]:
s = doc[2:5]
s

going to acquire

In [ ]:
type(s)

spacy.tokens.span.Span

In [ ]:
from spacy.tokens import Span

s1 = Span(doc, 0, 1, label="ORG")
s2 = Span(doc, 5, 6, label="ORG")

doc.set_ents([s1, s2], default="unmodified")
# save the changes in s1,s2 without modification in others indices

In [ ]:
for ent in doc.ents:
    print(ent.text, " | ", ent.label_)

Tesla  |  ORG
Twitter  |  ORG
$45 billion  |  MONEY


##using NLTK


1- ne_chunk >>> responsible for NER IN NLTK which take tags as an input

In [ ]:
import nltk
nltk.download('maxent_ne_chunker')
nltk.download('words')
from nltk import word_tokenize, pos_tag, ne_chunk

# Define input text
input_text = "Steve Jobs was the CEO of Apple Corp. in California."

# Tokenize input text
tokens = word_tokenize(input_text)

# Perform Part-of-Speech (POS) tagging
pos_tags = pos_tag(tokens)
print('-'*100)
print('pos_tags',pos_tags)
print('-'*100)

# Perform Named Entity Recognition (NER)
ne_tree = ne_chunk(pos_tags)
print('ne_tree',ne_tree)

----------------------------------------------------------------------------------------------------
pos_tags [('Steve', 'NNP'), ('Jobs', 'NNP'), ('was', 'VBD'), ('the', 'DT'), ('CEO', 'NNP'), ('of', 'IN'), ('Apple', 'NNP'), ('Corp.', 'NNP'), ('in', 'IN'), ('California', 'NNP'), ('.', '.')]
----------------------------------------------------------------------------------------------------
ne_tree (S
  (PERSON Steve/NNP)
  (PERSON Jobs/NNP)
  was/VBD
  the/DT
  (ORGANIZATION CEO/NNP)
  of/IN
  (ORGANIZATION Apple/NNP Corp./NNP)
  in/IN
  (GPE California/NNP)
  ./.)


[nltk_data] Downloading package maxent_ne_chunker to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package maxent_ne_chunker is already up-to-date!
[nltk_data] Downloading package words to /root/nltk_data...
[nltk_data]   Package words is already up-to-date!


In [ ]:
# Extract named entities and their labels
named_entities = []
for subtree in ne_tree.subtrees():
    if subtree.label() in ['PERSON', 'ORGANIZATION', 'LOCATION']:
        named_entity = ' '.join(word for word, tag in subtree.leaves())
        print(named_entity)
        named_entities.append((named_entity, subtree.label()))

# Print named entities and their labels
print(named_entities)

Steve
Jobs
CEO
Apple Corp.
[('Steve', 'PERSON'), ('Jobs', 'PERSON'), ('CEO', 'ORGANIZATION'), ('Apple Corp.', 'ORGANIZATION')]


In [ ]:
for word, tag in subtree.leaves():
    print(word)

California


#spell correction

1- using spellchecker()

2- using textblob()

In [ ]:
from textblob import TextBlob

# Create a TextBlob object with the text to correct
text = "I havv a goood speling!"

# Create a new TextBlob object with corrected spelling
corrected_text = TextBlob(text).correct()

# Print the corrected text
print(corrected_text)

I have a good spelling!


#BOW(Bag of words)

In [ ]:
paragraph =  """I have three visions for India. In 3000 years of our history, people from all over
               the world have come and invaded us, captured our lands, conquered our minds.
               From Alexander onwards, the Greeks, the Turks, the Moguls, the Portuguese, the British,
               the French, the Dutch, all of them came and looted us, took over what was ours.
               Yet we have not done this to any other nation. We have not conquered anyone.
               We have not grabbed their land, their culture,
               their history and tried to enforce our way of life on them.
               Why? Because we respect the freedom of others.That is why my
               first vision is that of freedom. I believe that India got its first vision of
               this in 1857, when we started the War of Independence. It is this freedom that
               we must protect and nurture and build on. If we are not free, no one will respect us.
               My second vision for India’s development. For fifty years we have been a developing nation.
               It is time we see ourselves as a developed nation. We are among the top 5 nations of the world
               in terms of GDP. We have a 10 percent growth rate in most areas. Our poverty levels are falling.
               Our achievements are being globally recognised today. Yet we lack the self-confidence to
               see ourselves as a developed nation, self-reliant and self-assured. Isn’t this incorrect?
               I have a third vision. India must stand up to the world. Because I believe that unless India
               stands up to the world, no one will respect us. Only strength respects strength. We must be
               strong not only as a military power but also as an economic power. Both must go hand-in-hand.
               My good fortune was to have worked with three great minds. Dr. Vikram Sarabhai of the Dept. of
               space, Professor Satish Dhawan, who succeeded him and Dr. Brahm Prakash, father of nuclear material.
               I was lucky to have worked with all three of them closely and consider this the great opportunity of my life.
               I see four milestones in my career"""

In [ ]:
import re
import nltk


nltk.download('punkt')
nltk.download('stopwords')
from nltk.corpus import stopwords

from nltk.stem.porter import PorterStemmer
from nltk.stem import WordNetLemmatizer
nltk.download('wordnet')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...


True

In [ ]:
# Cleaning the texts

stemmer = PorterStemmer()

lemitizer=WordNetLemmatizer()

sentences = nltk.sent_tokenize(paragraph) #split the paragraph to individual sentences based on spaces.

corpus = []

for i in range(len(sentences)): ##loop for each sentences individually

    review = re.sub('[^a-zA-Z]', ' ', sentences[i]) #replace any thing othwerwise characters with space
    review = review.lower()
    review = review.split()
    #review = [stemmer.stem(word) for word in review if not word in set(stopwords.words('english'))] #bad result
    review = [lemitizer.lemmatize(word) for word in review if not word in set(stopwords.words('english'))]
    review = ' '.join(review)
    corpus.append(review)
print(len(corpus))
corpus

31


['three vision india',
 'year history people world come invaded u captured land conquered mind',
 'alexander onwards greek turk mogul portuguese british french dutch came looted u took',
 'yet done nation',
 'conquered anyone',
 'grabbed land culture history tried enforce way life',
 '',
 'respect freedom others first vision freedom',
 'believe india got first vision started war independence',
 'freedom must protect nurture build',
 'free one respect u',
 'second vision india development',
 'fifty year developing nation',
 'time see developed nation',
 'among top nation world term gdp',
 'percent growth rate area',
 'poverty level falling',
 'achievement globally recognised today',
 'yet lack self confidence see developed nation self reliant self assured',
 'incorrect',
 'third vision',
 'india must stand world',
 'believe unless india stand world one respect u',
 'strength respect strength',
 'must strong military power also economic power',
 'must go hand hand',
 'good fortune worked

In [ ]:
# # Creating the Bag of Words model
# from sklearn.feature_extraction.text import CountVectorizer
# cv = CountVectorizer()
# x = cv.fit_transform(corpus)
# x

# #but x is still in sparse matrix shape

<31x114 sparse matrix of type '<class 'numpy.int64'>'
	with 155 stored elements in Compressed Sparse Row format>

In [ ]:
# Creating the Bag of Words model
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
x = cv.fit_transform(corpus).toarray()
print(x.shape)
x
#so we have 114 unique words

(31, 114)


array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 1, 1, 0],
       [0, 1, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

#N-GRAM

##UNi-GRAM

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

v = CountVectorizer()
v.fit(["Thor Hathodawala is looking for a job"])
v.vocabulary_

# give each word individually and it's index as a column
# by default(one gram)
# using fit function not fit_transform

{'thor': 5, 'hathodawala': 1, 'is': 2, 'looking': 4, 'for': 0, 'job': 3}

In [ ]:
v = CountVectorizer(ngram_range=(1,1))
v.fit(["Thor Hathodawala is looking for a job"])
v.vocabulary_

{'thor': 5, 'hathodawala': 1, 'is': 2, 'looking': 4, 'for': 0, 'job': 3}

##BI-GRAM

In [ ]:
v = CountVectorizer(ngram_range=(1,2))
v.fit(["Thor Hathodawala is looking for a job"])
v.vocabulary_

{'thor': 9,
 'hathodawala': 2,
 'is': 4,
 'looking': 7,
 'for': 0,
 'job': 6,
 'thor hathodawala': 10,
 'hathodawala is': 3,
 'is looking': 5,
 'looking for': 8,
 'for job': 1}

In [ ]:
v = CountVectorizer(ngram_range=(1,3))
v.fit(["Thor Hathodawala is looking for a job"])
v.vocabulary_

{'thor': 12,
 'hathodawala': 2,
 'is': 5,
 'looking': 9,
 'for': 0,
 'job': 8,
 'thor hathodawala': 13,
 'hathodawala is': 3,
 'is looking': 6,
 'looking for': 10,
 'for job': 1,
 'thor hathodawala is': 14,
 'hathodawala is looking': 4,
 'is looking for': 7,
 'looking for job': 11}

##Task :

1- remove stop words

2- lemmatize the text

3- apply n-gram

In [ ]:
corpus = [
    "Thor ate pizza",
    "Loki is tall",
    "Loki is eating pizza"
]

In [ ]:
import spacy

# load english language model
nlp = spacy.load("en_core_web_sm")

def preprocess(text):
    # remove stop words and lemmatize the text
    doc = nlp(text)
    filtered_tokens = []
    for token in doc:
        if token.is_stop or token.is_punct:
            continue
        filtered_tokens.append(token.lemma_)

    return " ".join(filtered_tokens)

In [ ]:
preprocess("Thor ate pizza")


'thor eat pizza'

In [ ]:
preprocess("Loki is eating pizza")


'Loki eat pizza'

In [ ]:
corpus_processed = [
    preprocess(text) for text in corpus
]
corpus_processed

['thor eat pizza', 'Loki tall', 'Loki eat pizza']

In [ ]:
v = CountVectorizer(ngram_range=(1,2))
v.fit(corpus_processed)
v.vocabulary_

{'thor': 7,
 'eat': 0,
 'pizza': 5,
 'thor eat': 8,
 'eat pizza': 1,
 'loki': 2,
 'tall': 6,
 'loki tall': 4,
 'loki eat': 3}

In [ ]:
# fit >>>> take all the documents.
# transform  >>> take sentence that you want to encode it.
v.transform(["Thor eat pizza"]).toarray()

array([[1, 1, 0, 0, 0, 1, 0, 1, 1]])

In [ ]:
v.transform(["Hulk eat pizza"]).toarray()

array([[1, 1, 0, 0, 0, 1, 0, 0, 0]])

#TF-IDF

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
import pandas as pd

In [ ]:
# Example documents
docs = [
  "The quick brown fox jumps over the lazy dog.",
  "A stitch in time saves nine.",
  "The early bird catches the worm.",
  "Actions speak louder than words.",
]

In [ ]:
# Create a TF-IDF vectorizer instance
tfidf = TfidfVectorizer()

# Fit the vectorizer to the documents
tfidf.fit(docs)

# Transform the documents into a TF-IDF matrix
tfidf_matrix = tfidf.transform(docs)
print(tfidf_matrix.toarray())

# YOU CAN MAKE IT IN ONE LINE using fit_transform.

[[0.         0.         0.32467583 0.         0.32467583 0.
  0.32467583 0.         0.32467583 0.32467583 0.         0.
  0.32467583 0.32467583 0.         0.         0.         0.
  0.5119563  0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.4472136  0.         0.         0.         0.4472136
  0.         0.         0.4472136  0.         0.4472136  0.
  0.         0.4472136  0.         0.        ]
 [0.         0.39264414 0.         0.39264414 0.         0.39264414
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.6191303  0.         0.         0.39264414]
 [0.4472136  0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.4472136  0.
  0.         0.         0.         0.4472136  0.         0.4472136
  0.         0.         0.4472136  0.        ]]


When sklearn.__version__ <= 0.24.x use following method

get_feature_names()


When sklearn.__version__ >= 1.0.x use following method

get_feature_names_out()

In [ ]:
# Convert the matrix to a pandas dataframe
df_tfidf = pd.DataFrame(tfidf_matrix.toarray(), columns=tfidf.get_feature_names_out())

# Display the dataframe
print(df_tfidf)


# will make every unique word as a feature, so because i have 22 columns.
# noticed, the most frequency word is the least value of TF-IDF

    actions      bird     brown   catches       dog     early       fox  \
0  0.000000  0.000000  0.324676  0.000000  0.324676  0.000000  0.324676   
1  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
2  0.000000  0.392644  0.000000  0.392644  0.000000  0.392644  0.000000   
3  0.447214  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   

         in     jumps      lazy  ...      over     quick     saves     speak  \
0  0.000000  0.324676  0.324676  ...  0.324676  0.324676  0.000000  0.000000   
1  0.447214  0.000000  0.000000  ...  0.000000  0.000000  0.447214  0.000000   
2  0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000  0.000000   
3  0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000  0.447214   

     stitch      than       the      time     words      worm  
0  0.000000  0.000000  0.511956  0.000000  0.000000  0.000000  
1  0.447214  0.000000  0.000000  0.447214  0.000000  0.000000  
2  0.000000  0.000000  0.619130

## the numbers of uniques words(min_df)

1- min_df>>>>>>> will control the numbers of words which will be appeared based on numbers of frequency

In [ ]:
#the default of min_df is one
doc1 = "the quick brown fox"
doc2 = "the lazy dog"
doc3 = "the quick brown cat"

cv = TfidfVectorizer()
X = cv.fit_transform([doc1, doc2, doc3])
print(cv.get_feature_names_out())  # ['brown', 'cat', 'dog', 'fox', 'lazy', 'quick', 'the']
print(X.toarray())

['brown' 'cat' 'dog' 'fox' 'lazy' 'quick' 'the']
[[0.4804584  0.         0.         0.63174505 0.         0.4804584
  0.37311881]
 [0.         0.         0.65249088 0.         0.65249088 0.
  0.38537163]
 [0.4804584  0.63174505 0.         0.         0.         0.4804584
  0.37311881]]


In [ ]:
cv = TfidfVectorizer(min_df=2)
X = cv.fit_transform([doc1, doc2, doc3])
print(cv.get_feature_names_out())  # ['brown', 'quick', 'the']
print(X.toarray())

#noticed thatcat,dog,fox,lazy]>>>>>> not appeared becuse the numbers of repeats less than two

['brown' 'quick' 'the']
[[0.61980538 0.61980538 0.48133417]
 [0.         0.         1.        ]
 [0.61980538 0.61980538 0.48133417]]


In [ ]:
cv = TfidfVectorizer(min_df=2,stop_words='english')
X = cv.fit_transform([doc1, doc2, doc3])
print(cv.get_feature_names_out())  # ['brown', 'quick', 'the']
print(X.toarray())

#noticed that [the]>>>>>>>>not appeared becuse it is from stop_word

['brown' 'quick']
[[0.70710678 0.70710678]
 [0.         0.        ]
 [0.70710678 0.70710678]]


##Another Example

In [ ]:
text=["Hi How are you How are you doing","Hi what's up","Wow that's awesome"]
cv = TfidfVectorizer(min_df=1)
x_traincv = cv.fit_transform(text)
feature_names = cv.get_feature_names_out()

# Print the feature names and the TF-IDF matrix
print(feature_names)
print(x_traincv.toarray())

['are' 'awesome' 'doing' 'hi' 'how' 'that' 'up' 'what' 'wow' 'you']
[[0.54275734 0.         0.27137867 0.20639047 0.54275734 0.
  0.         0.         0.         0.54275734]
 [0.         0.         0.         0.4736296  0.         0.
  0.62276601 0.62276601 0.         0.        ]
 [0.         0.57735027 0.         0.         0.         0.57735027
  0.         0.         0.57735027 0.        ]]


In [ ]:
#Another Example

text=["Hi How are you How are you doing","Hi what's up","Wow that's awesome"]
cv = TfidfVectorizer(min_df=1,stop_words='english')
x_traincv = cv.fit_transform(text)
feature_names = cv.get_feature_names_out()

# Print the feature names and the TF-IDF matrix
print(feature_names)
print(x_traincv.toarray())

['awesome' 'doing' 'hi' 'wow']
[[0.         0.79596054 0.60534851 0.        ]
 [0.         0.         1.         0.        ]
 [0.70710678 0.         0.         0.70710678]]


#Word Embedding

### Word Embedding Techniques using Embedding Layer in Keras

In [ ]:
### Libraries USed Tensorflow> 2.0  and keras

In [ ]:
##tensorflow >2.0
from tensorflow.keras.preprocessing.text import one_hot

In [ ]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [ ]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

1-  In general, a larger vocabulary size allows for a more nuanced representation of the language, but it also increases the computational cost of training the embedding model. On the other hand, a smaller vocabulary size may limit the expressiveness of the embeddings and reduce the accuracy of the trained model.

2- A reasonable starting point for a vocabulary size is around 20,000 to 30,000, but this may need to be adjusted up or down depending on your specific use case. If you have a smaller dataset or are working with a less complex language, you may be able to use a smaller vocabulary size

In [ ]:
### Vocabulary size>>>> the size of one hot encoding
voc_size=10000

#### One Hot Representation

In [ ]:
#will make one hot encoding and return each sentence with it's indices

onehot_repr=[one_hot(words,voc_size)for words in sent]
print(onehot_repr)


#[2725, 4751, 1322, 7778] >>>>>the glass of milk

[[2725, 4751, 1322, 7778], [2725, 4751, 1322, 8804], [2725, 4234, 1322, 5633], [1577, 8806, 7300, 4252, 1890], [1577, 8806, 7300, 4252, 900], [5473, 2725, 6925, 1322, 1240], [4436, 7782, 7303, 4252]]


### Word Embedding Represntation

In [ ]:
import numpy as np
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

1- here, we will pass the result of one hot to embedding layer.

2- but not all the sentences have same numbers of words , so i will make padding.

3- padding='pre' or 'post'>>>> the zeros before or after indices to be same size.

4- The choice of padding can affect the performance of the model, depending on the nature of the data. For example, if the end of the sequence is more important for the task at hand, you may want to use padding='pre' to preserve the order of the original sequence. On the other hand, if the beginning of the sequence is more important, you may want to use padding='post'. In some cases, it may be useful to try both options and see which one works better for your particular task.

In [ ]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 2725 4751 1322 7778]
 [   0    0    0    0 2725 4751 1322 8804]
 [   0    0    0    0 2725 4234 1322 5633]
 [   0    0    0 1577 8806 7300 4252 1890]
 [   0    0    0 1577 8806 7300 4252  900]
 [   0    0    0 5473 2725 6925 1322 1240]
 [   0    0    0    0 4436 7782 7303 4252]]


In [ ]:
dim=10

# tis is the attributes which will compare the words with them.

In [ ]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [ ]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 8, 10)             100000    
                                                                 
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [ ]:
print(model.predict(embedded_docs))
#there are the features would be used in the models

1/1 [==============================] - 0s 49ms/step
[[[-0.00920211 -0.00609029 -0.04967015 -0.00404746  0.0109743
   -0.02600037  0.04772934 -0.03560144 -0.03376504 -0.00454193]
  [-0.00920211 -0.00609029 -0.04967015 -0.00404746  0.0109743
   -0.02600037  0.04772934 -0.03560144 -0.03376504 -0.00454193]
  [-0.00920211 -0.00609029 -0.04967015 -0.00404746  0.0109743
   -0.02600037  0.04772934 -0.03560144 -0.03376504 -0.00454193]
  [-0.00920211 -0.00609029 -0.04967015 -0.00404746  0.0109743
   -0.02600037  0.04772934 -0.03560144 -0.03376504 -0.00454193]
  [-0.03650075  0.03408836 -0.04835917 -0.03642067  0.03801862
    0.04609648  0.04647345 -0.04785673 -0.00879307  0.00588372]
  [ 0.04637647  0.04674262  0.02558163  0.02132613 -0.00860794
    0.02643653  0.02292861  0.04576779  0.04208876  0.03885684]
  [ 0.00605949  0.0075675   0.04031825 -0.00727053 -0.0169364
   -0.02045926  0.00146352  0.03443665 -0.04293823  0.04288236]
  [-0.04474065 -0.00670535 -0.01946297 -0.04355031  0.0459247
  

In [ ]:
#frist sentence after onehot + padding
embedded_docs[0]

array([   0,    0,    0,    0, 2725, 4751, 1322, 7778], dtype=int32)

In [ ]:
#frist sentence after embedding
print(model.predict(embedded_docs)[0])

1/1 [==============================] - 0s 24ms/step
[[-0.00920211 -0.00609029 -0.04967015 -0.00404746  0.0109743  -0.02600037
   0.04772934 -0.03560144 -0.03376504 -0.00454193]
 [-0.00920211 -0.00609029 -0.04967015 -0.00404746  0.0109743  -0.02600037
   0.04772934 -0.03560144 -0.03376504 -0.00454193]
 [-0.00920211 -0.00609029 -0.04967015 -0.00404746  0.0109743  -0.02600037
   0.04772934 -0.03560144 -0.03376504 -0.00454193]
 [-0.00920211 -0.00609029 -0.04967015 -0.00404746  0.0109743  -0.02600037
   0.04772934 -0.03560144 -0.03376504 -0.00454193]
 [-0.03650075  0.03408836 -0.04835917 -0.03642067  0.03801862  0.04609648
   0.04647345 -0.04785673 -0.00879307  0.00588372]
 [ 0.04637647  0.04674262  0.02558163  0.02132613 -0.00860794  0.02643653
   0.02292861  0.04576779  0.04208876  0.03885684]
 [ 0.00605949  0.0075675   0.04031825 -0.00727053 -0.0169364  -0.02045926
   0.00146352  0.03443665 -0.04293823  0.04288236]
 [-0.04474065 -0.00670535 -0.01946297 -0.04355031  0.0459247   0.01831294

In [ ]:
print(model.predict(embedded_docs)[1])

1/1 [==============================] - 0s 22ms/step
[[-0.00920211 -0.00609029 -0.04967015 -0.00404746  0.0109743  -0.02600037
   0.04772934 -0.03560144 -0.03376504 -0.00454193]
 [-0.00920211 -0.00609029 -0.04967015 -0.00404746  0.0109743  -0.02600037
   0.04772934 -0.03560144 -0.03376504 -0.00454193]
 [-0.00920211 -0.00609029 -0.04967015 -0.00404746  0.0109743  -0.02600037
   0.04772934 -0.03560144 -0.03376504 -0.00454193]
 [-0.00920211 -0.00609029 -0.04967015 -0.00404746  0.0109743  -0.02600037
   0.04772934 -0.03560144 -0.03376504 -0.00454193]
 [-0.03650075  0.03408836 -0.04835917 -0.03642067  0.03801862  0.04609648
   0.04647345 -0.04785673 -0.00879307  0.00588372]
 [ 0.04637647  0.04674262  0.02558163  0.02132613 -0.00860794  0.02643653
   0.02292861  0.04576779  0.04208876  0.03885684]
 [ 0.00605949  0.0075675   0.04031825 -0.00727053 -0.0169364  -0.02045926
   0.00146352  0.03443665 -0.04293823  0.04288236]
 [-0.02535597  0.04952774  0.02960017 -0.04968152  0.04142809  0.03051211